{{- range $key, $val := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $val.name }}
  namespace: {{ $.Values.global.namespace | default "default" }}
  labels:
    app: {{ $val.name }}
spec:
  replicas: {{ $val.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $val.name }}
  template:
    metadata:
      labels:
        app: {{ $val.name }}
    spec:
      containers:
      - name: {{ $val.name }}
        image: "{{ $val.image.repository }}:{{ $val.image.tag | default "latest" }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ $val.targetPort }}
          name: http
        env:
        - name: DB_HOST
          value: {{ $.Values.global.postgresql.host | quote }}
        - name: DB_USER
          value: {{ $.Values.global.postgresql.user | quote }}
        - name: DB_PASSWORD
          value: {{ $.Values.global.postgresql.password | quote }}
        - name: DB_NAME
          value: {{ $.Values.global.postgresql.database | quote }}
        resources:
          limits:
            cpu: {{ $.Values.resources.limits.cpu }}
            memory: {{ $.Values.resources.limits.memory }}
          requests:
            cpu: {{ $.Values.resources.requests.cpu }}
            memory: {{ $.Values.resources.requests.memory }}
{{- end }}
