{{- range $key, $val := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $val.name }}
  namespace: {{ $.Values.global.namespace | default "default" }}
  labels:
    app: {{ $val.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ $val.port }}
    targetPort: {{ $val.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ $val.name }}
{{- end }}
