version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservices_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d microservices_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build: ./user-service
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy

  product-service:
    build: ./product-service
    ports:
      - "8002:8000"
    depends_on:
      postgres:
        condition: service_healthy

  order-service:
    build: ./order-service
    ports:
      - "8003:8000"
    depends_on:
      postgres:
        condition: service_healthy

  payment-service:
    build: ./payment-service
    ports:
      - "8004:8000"
    depends_on:
      postgres:
        condition: service_healthy

  inventory-service:
    build: ./inventory-service
    ports:
      - "8005:8000"
    depends_on:
      postgres:
        condition: service_healthy